# Development Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_shop_dev
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jwt:
  secret: dev-secret-key-not-for-production
  expiration: 3600000  # 1 hour
logging:
  level:
    com.coffeeshop: DEBUG
    org.springframework.security: DEBUG