# Development Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_shop_dev
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jwt:
  secret: jbBPt/gT9n3NRZCn9Vj4ptqIv0VAyB4KvNkWfo707MKR5ZWx6wL/giDHQa191P72XfbXWmWuOe1Us8DcgX9u2w==
  expiration: 3600000  # 1 hour
logging:
  level:
    com.coffee_management_system: DEBUG
    org.springframework.security: DEBUG