# Test Configuration
spring:
  mail:
    host: localhost
    port: 25
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.coffeeshop.email: DEBUG